import { useState } from 'react'
import { ArrowDown, ArrowRight, ArrowUpRight, Check, Instagram, Menu, Music2, Quote, Sparkles, X } from 'lucide-react'

const danceClasses = [
  { number: '01', name: 'Little movers', style: 'First steps & play', ages: 'Ages 2–4', color: 'lilac', image: 'https://images.unsplash.com/photo-1518834107812-67b0b7c58434?auto=format&fit=crop&w=1000&q=85' },
  { number: '02', name: 'Ballet & pointe', style: 'Grace & technique', ages: 'Ages 5+', color: 'peach', image: 'https://images.unsplash.com/photo-1504609813442-a8924e83f76e?auto=format&fit=crop&w=1000&q=85' },
  { number: '03', name: 'Jazz & hip-hop', style: 'Big energy, big smiles', ages: 'Ages 7+', color: 'yellow', image: 'https://images.unsplash.com/photo-1547153760-18fc86324498?auto=format&fit=crop&w=1000&q=85' },
  { number: '04', name: 'Contemporary', style: 'Move your own way', ages: 'Teens & adults', color: 'sage', image: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1000&q=85' },
]
const weekSchedule = [
  { day: 'Mon', time: '4:00 pm', name: 'Little ballet', age: 'Ages 3–5' },
  { day: 'Mon', time: '5:15 pm', name: 'Jazz foundations', age: 'Ages 7–10' },
  { day: 'Tue', time: '4:30 pm', name: 'Ballet & pointe', age: 'Ages 11–16' },
  { day: 'Wed', time: '5:00 pm', name: 'Hip-hop crew', age: 'Ages 8–12' },
  { day: 'Thu', time: '6:15 pm', name: 'Contemporary flow', age: 'Teens & adults' },
]
function Brand({ light = false }) {
  return <a href="#home" className={`brand ${light ? 'brand-light' : ''}`} aria-label="Grace Dance Studio home"><span className="brand-mark"><Music2 size={21} strokeWidth={1.65} /></span><span className="brand-name">grace<span>dance studio</span></span></a>
}
function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [activeDay, setActiveDay] = useState('All')
  const [submitted, setSubmitted] = useState(false)
  const [email, setEmail] = useState('')
  const visibleClasses = activeDay === 'All' ? weekSchedule : weekSchedule.filter((item) => item.day === activeDay)
  const closeMenu = () => setMenuOpen(false)
  function handleSubscribe(event) { event.preventDefault(); if (!email.trim()) return; setSubmitted(true) }
  return <>
    <div className="announcement-bar"><span><Sparkles size={13} /> Fall classes are open!</span><a href="#classes">Find your happy place <ArrowRight size={13} /></a><span className="announcement-side">Spots are filling up — find your flow.</span></div>
    <header className="site-header"><nav className="nav-shell" aria-label="Main navigation"><Brand /><div className="desktop-nav"><a href="#classes">Classes</a><a href="#our-story">Our studio</a><a href="#schedule">Schedule</a><a href="#community">Community</a></div><a className="button button-small button-dark header-cta" href="#contact">Come say hello <ArrowUpRight size={15} /></a><button className="mobile-menu-toggle" aria-label={menuOpen ? 'Close navigation' : 'Open navigation'} onClick={() => setMenuOpen((open) => !open)}>{menuOpen ? <X size={23} /> : <Menu size={23} />}</button></nav>{menuOpen && <div className="mobile-nav"><a href="#classes" onClick={closeMenu}>Classes</a><a href="#our-story" onClick={closeMenu}>Our studio</a><a href="#schedule" onClick={closeMenu}>Schedule</a><a href="#community" onClick={closeMenu}>Community</a><a href="#contact" className="button button-dark" onClick={closeMenu}>Come say hello <ArrowUpRight size={15} /></a></div>}</header>
    <main>
      <section className="hero" id="home"><div className="hero-grain" /><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot" /> Your neighborhood dance studio · Austin, TX</div><h1>Find your<br />flow. <em>Find your</em><br /><em>people.</em></h1><p className="hero-description">A little movement can change everything. Come dance, make friends, and feel more like yourself — right where you are.</p><div className="hero-actions"><a className="button button-dark" href="#classes">Explore our classes <ArrowUpRight size={16} /></a><a className="text-link" href="#our-story">Meet your new happy place <ArrowRight size={15} /></a></div><div className="hero-proof"><div className="avatar-stack" aria-hidden="true"><img src="https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=72&h=72&q=80" alt="" /><img src="https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=72&h=72&q=80" alt="" /><img src="https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=72&h=72&q=80" alt="" /><img src="https://images.unsplash.com/photo-1552058544-f2b08422138a?auto=format&fit=crop&w=72&h=72&q=80" alt="" /></div><span><strong>200+</strong> happy dancers & counting</span></div><span className="hero-note">A place to take up space <span>↗</span></span></div><div className="hero-art" aria-label="Dancers moving together in a sunlit studio"><div className="hero-image"><img src="https://images.unsplash.com/photo-1504609813442-a8924e83f76e?auto=format&fit=crop&w=1300&q=90" alt="Dancers moving together in a sunlit studio" /></div><div className="hero-sticker"><span>Move</span><span className="sticker-star">✳</span><span>with joy</span></div><div className="image-caption"><span className="caption-line" /> Room to grow. Room to glow.</div><div className="hero-sparkle">✳</div></div><a className="scroll-cue" href="#classes"><span>Keep exploring</span><ArrowDown size={14} /></a></section>
      <section className="classes-section section-wrap" id="classes"><div className="section-heading"><div><div className="eyebrow"><span className="eyebrow-dot" /> There’s a spot for you here</div><h2>Come as you are.<br /><em>Move how you feel.</em></h2></div><div className="heading-aside"><p>From first twirls to finding your rhythm, our classes give everyone room to grow in their own way.</p><a className="text-link" href="#schedule">View the schedule <ArrowRight size={15} /></a></div></div><div className="class-grid">{danceClasses.map((danceClass) => <a className="class-card" href="#schedule" key={danceClass.number}><div className={`class-image class-image-${danceClass.color}`}><img src={danceClass.image} alt={`${danceClass.name} class at Grace Dance Studio`} loading="lazy" /><span className="class-number">{danceClass.number}</span><span className="class-arrow"><ArrowUpRight size={17} /></span><span className="class-age">{danceClass.ages}</span></div><div className="class-card-copy"><div><h3>{danceClass.name}</h3><p>{danceClass.style}</p></div><ArrowRight size={17} className="class-card-link" /></div></a>)}</div><div className="classes-footer"><span>Big feelings. Bigger moves. A very good time.</span><a href="#schedule" className="mini-link">We can’t wait to meet you <ArrowRight size={14} /></a></div></section>
      <section className="story-section" id="our-story"><div className="story-content section-wrap"><div className="story-photos"><img className="story-main-photo" src="https://images.unsplash.com/photo-1524594152303-9fd13543fe6e?auto=format&fit=crop&w=950&q=85" alt="Dancer stretching beside a sunlit window" loading="lazy" /><img className="story-small-photo" src="https://images.unsplash.com/photo-1486308510493-aa64833637bc?auto=format&fit=crop&w=540&q=85" alt="Close-up of ballet slippers" loading="lazy" /><div className="story-photo-note"><span>Good people.</span><br /><em>Good energy.</em></div><span className="story-sparkle">✳</span></div><div className="story-copy"><div className="eyebrow"><span className="eyebrow-dot" /> A little about us</div><h2>We believe dance is for <em>every body.</em></h2><p>Not just the perfect days or the perfect moves. We’re here for the belly laughs, the brave first tries, the deep breaths, and that feeling when a song just gets you.</p><p>Grace is a neighborhood studio for people of all ages, backgrounds, and experience levels. Come as you are — the rest will find its rhythm.</p><a className="button button-dark" href="#contact">Get to know us <ArrowUpRight size={16} /></a><div className="studio-stat"><strong>10<span>+</span></strong><span>years of good<br />moves & good people</span></div></div></div><div className="values-strip"><span><span>✳</span> All bodies belong</span><span><span>✳</span> Progress over perfect</span><span><span>✳</span> Joy is the whole point</span><span><span>✳</span> We move together</span></div></section>
      <section className="schedule-section section-wrap" id="schedule"><div className="schedule-intro"><div className="eyebrow"><span className="eyebrow-dot" /> Good things happen on the regular</div><h2>Find your<br /><em>time to shine.</em></h2><p>A few good places to start. New to dance? We’ll help you find the right fit.</p><a className="button button-dark" href="#contact">Help me find a class <ArrowUpRight size={16} /></a><div className="schedule-note"><span className="note-mark">✳</span><span>Can’t make it this week?<br />Let’s figure something out.</span></div></div><div className="schedule-list-wrap"><div className="schedule-list-head"><div><span>On the studio floor</span><span className="open-tag"><span /> A few favorite classes</span></div><div className="day-filters" aria-label="Filter schedule by day">{['All', 'Mon', 'Tue', 'Wed', 'Thu'].map((day) => <button key={day} className={activeDay === day ? 'filter-active' : ''} onClick={() => setActiveDay(day)}>{day}</button>)}</div></div><div className="schedule-rows">{visibleClasses.map((item) => <a className="schedule-row" key={`${item.day}-${item.name}`} href="#contact"><span className="schedule-day">{item.day}</span><span className="schedule-time">{item.time}</span><span className="schedule-name"><strong>{item.name}</strong><small>{item.age}</small></span><span className="schedule-arrow"><ArrowUpRight size={17} /></span></a>)}</div><div className="schedule-legend"><span>* All levels welcome unless noted. Absolutely no dance experience needed.</span><a href="#contact">See the full weekly schedule <ArrowRight size={14} /></a></div></div></section>
      <section className="testimonial-section" id="community"><div className="quote-decoration">“</div><div className="testimonial-inner"><div className="eyebrow"><span className="eyebrow-dot" /> The best part is the people</div><blockquote>“I walked in nervous and walked out already planning what I’d wear next week. Grace feels like coming home to a room full of people rooting for you.”</blockquote><div className="quote-credit"><div className="credit-avatar"><img src="https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=96&h=96&q=80" alt="" loading="lazy" /></div><div><strong>Jamie R.</strong><span>Contemporary dancer · Here for 2 years</span></div><span className="quote-stars">★★★★★</span></div></div><div className="quote-aside"><Quote size={20} /><span>Real moves.<br />Real people.<br /><em>Real joy.</em></span></div></section>
      <section className="cta-section" id="contact"><div className="cta-inner section-wrap"><div className="cta-copy"><div className="eyebrow"><span className="eyebrow-dot" /> Your first class is on us</div><h2>So… ready<br />to <em>move?</em></h2><p>You don’t need a plan or special shoes. Just a little curiosity. We’ll take it from there.</p><a className="button button-light" href="mailto:hello@gracedance.studio?subject=Let%E2%80%99s%20try%20a%20class">Book your free first class <ArrowUpRight size={16} /></a><span className="cta-footnote"><Check size={14} /> No pressure. No commitment. Just a good time.</span></div><div className="cta-art"><img src="https://images.unsplash.com/photo-1535525153412-5a42439a210d?auto=format&fit=crop&w=1000&q=85" alt="Friends share a joyful moment in the dance studio" loading="lazy" /><div className="cta-bubble">✳<span>There’s room<br />for you.</span></div></div></div><div className="cta-decoration cta-decoration-one">✳</div><div className="cta-decoration cta-decoration-two">✳</div></section>
    </main>
    <footer className="site-footer"><div className="footer-main section-wrap"><div className="footer-brand-col"><Brand light /><p>Dance, good people, and finding your flow — right here in Austin.</p><a className="instagram-link" href="https://instagram.com" target="_blank" rel="noreferrer"><Instagram size={17} /><span>Follow along <ArrowUpRight size={12} /></span></a></div><div className="footer-col"><h4>Come find us</h4><a href="https://maps.google.com/?q=220+E+6th+St,+Austin,+TX+78701" target="_blank" rel="noreferrer">220 E. 6th Street<br />Austin, TX 78701</a><span>Right around the corner, right on beat.</span></div><div className="footer-col"><h4>Say hello</h4><a href="mailto:hello@gracedance.studio">hello@gracedance.studio</a><a href="tel:+15125550146">(512) 555-0146</a><span>Mon–Fri, 9am–6pm</span></div><div className="footer-newsletter"><h4>Good things in your inbox</h4><p>Studio news, new classes & the occasional happy dance.</p><form onSubmit={handleSubscribe}><label className="sr-only" htmlFor="newsletter-email">Your email address</label><input id="newsletter-email" type="email" placeholder="Your email address" value={email} onChange={(event) => { setEmail(event.target.value); setSubmitted(false) }} required /><button type="submit" aria-label="Subscribe to the newsletter"><ArrowRight size={18} /></button></form>{submitted && <span className="subscribe-success"><Check size={13} /> You’re on the list. See you soon!</span>}</div></div><div className="footer-bottom section-wrap"><span>© 2025 Grace Dance Studio. Made with a little love & a lot of music.</span><div><a href="#home">Back to top ↑</a><span>Good moves for everyone.</span></div></div></footer>
  </>
}
export default App
